#!/bin/sh
# https://faq.i3wm.org/question/6299/repeat-or-history-for-dmenu-commands.1.html


cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
histsize=50
if [ -d "$cachedir" ]; then
    cache=$cachedir/emenu
    hist=$cachedir/emenu_hist
else
    cache=$HOME/.emenu_cache # if no xdg dir, fall back to dotfile in ~
    hist=$HOME/.emenu_cache_hist # if no xdg dir, fall back to dotfile in ~
fi
if [ ! -e "$hist" ]; then
    touch "$hist"
    echo foo
fi
cmd=$(
    IFS=:
    if stest -dqr -n "$cache" $PATH; then
        (tac "$hist" ; stest -flx $PATH | sort -u | tee "$cache" ) | dmenu "$@" -b -f -nb '#fdf6e3' -nf '#657b83' -sb '#859900' -sf '#cb4b16' -fn FiraCode
    else
        (tac "$hist"; cat "$cache") | dmenu "$@" -b -f -nb '#fdf6e3' -nf '#657b83' -sb '#859900' -sf '#cb4b16' -fn FiraCode
    fi
    ) 

echo "$cmd" | ${SHELL:-"/bin/sh"} &
#i3-msg "exec $cmd"

sed -i -e "/^${cmd}$/d;${histsize}q" "$hist"
echo "$cmd" >> "$hist"
