#! /bin/bash

TCOL="#859900"   
ACOL="#6c71c4"   
PCOL="#586e75"

MPDSTATE=$(mpc | sed -e '2 !d' -e 's/^.*\[//' -e 's/\].*$//')

if [ $MPDSTATE == "playing" ]; then
    echo "<fc=$ACOL>$(mpc current | sed "s/ - /\<\/fc\> - \<fc=$TCOL>/")</fc>"
elif [ $MPDSTATE == "paused" ]; then
    echo "<fc=$PCOL>$(mpc current)</fc>"
fi
