#!/bin/sh
# https://faq.i3wm.org/question/6299/repeat-or-history-for-dmenu-commands.1.html

config_1="$XDG_CONFIG_HOME/herbstluftwm/herbstcommander"
config_2="$HOME/.config/herbstluftwm/herbstcommander"
[[ -f "$config_1" ]] && source "$config_1"
[[ -f "$config_2" ]] && source "$config_2"

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
histsize=50
if [ -d "$cachedir" ]; then
    cache=$cachedir/emenu
    hist=$cachedir/emenu_hist
else
    cache=$HOME/.emenu_cache # if no xdg dir, fall back to dotfile in ~
    hist=$HOME/.emenu_cache_hist # if no xdg dir, fall back to dotfile in ~
fi
if [ ! -e "$hist" ]; then
    touch "$hist"
    echo foo
fi
cmd=$(
    IFS=:
    if stest -dqr -n "$cache" $PATH; then
        (tac "$hist" ; stest -flx $PATH | sort -u | tee "$cache" ) | dmenu "$@" -b -f -nb '#002b36' -nf '#657b83' -sb '#002b36' -sf '#268bd2' -fn Sans
    else
        (tac "$hist"; cat "$cache") | dmenu "$@" -b -f -nb '#002b36' -nf '#657b83' -sb '#002b36' -sf '#268bd2' -fn Sans
    fi
    ) 

echo "$cmd" | ${SHELL:-"/bin/sh"} &
#i3-msg "exec $cmd"

sed -i -e "/^${cmd}$/d;${histsize}q" "$hist"
echo "$cmd" >> "$hist"
