#! /bin/bash

TCOL="#586e75"   
ACOL="#cb4b16"   
DCOL="#b58900"   
PCOL="#859900"   

MOCSTATE=$(mocp --info | head -n 1 | tail -c +8)

if [ $MOCSTATE == "PLAY" ]; then
  # MOC playing
  echo "<fc=$ACOL>$(mocp --info | tail -n +4 | head -n 1 | \
       tail -c +9)</fc> <fc=$DCOL>-</fc> <fc=$TCOL>$(mocp --info | \
       tail -n +5 | head -n 1 | tail -c +12)</fc>"

elif [ $MOCSTATE == "PAUSE" ]; then
  # MOC pause
  echo "<fc=$PCOL>$(mocp --info | tail -n +4 | head -n 1 | \
       tail -c +9) - $(mocp --info | tail -n +5 | head -n 1 | tail -c +12)</fc>"
fi
